### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

### ISSUE THREAD

**Issue by yl642** [dward2/BME547#156]
I tried to run this code on my Mac, and I modified following line to populate with my string: 

https://github.com/dward2/BME547/blob/38ecae50f648dcde0d34e50c5da935cafdae2440/Resources/Databases/mongo_db_example.py#L8

But pycharm gave me this error:
pymongo.errors.ServerSelectionTimeoutError: bme547yl642-shard-00-00-ctboh.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056),bme547yl642-shard-00-02-ctboh.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056),bme547yl642-shard-00-01-ctboh.mongodb.net:27017: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)

However, it did work well when I ran this connecting in jupyter notebook.

**Comment by dward2** [comment]
FYI, if you were not able to make me an assignee on the issue, another way to make sure I am alerted about an issue post is to include @dward2 in the note.  For example, I am adding @yl642  to this so you will be tagged.

**Comment by dward2** [comment]
@yl642 Are you using a Mac?

**Comment by dward2** [comment]
In the string above, if you just replaced the <> portions, it still won't work.  That is because the `-nlfrn` portion of the string is also specific to your database.  So, instead of just populating the <>, you should copy the connect string from your MongoDB Atlas online account where you get the connection string as described in Step 11 here:  <https://github.com/dward2/BME547/blob/master/Resources/Databases/mlab.md#setup>

**Comment by yl642** [comment]
@dward2 yes, I am using a MAC

**Comment by yl642** [comment]
> In the string above, if you just replaced the <> portions, it still won't work. That is because the `-nlfrn` portion of the string is also specific to your database. So, instead of just populating the <>, you should copy the connect string from your MongoDB Atlas online account where you get the connection string as described in Step 11 here: https://github.com/dward2/BME547/blob/master/Resources/Databases/mlab.md#setup

I did so, and it worked well in jupyter notebook, but not pycharm with the exact same string

**Comment by dward2** [comment]
@yl642 Some people when using Macs and trying to access other web resources have this kind of certificate error.

Visit this page:
<https://github.com/dward2/BME547/blob/2019b_Fall/Assignments/heart_rate_sentinel_server_assignment.md#special-note-for-mac-users>.  This is the version of the Heart Rate Sentinel Server assignment from previous semesters where I have some instructions for Mac users about addressing this problem.  Give it a try and please let me know if this helps.

**Comment by yl642** [comment]
> @yl642 Some people when using Macs and trying to access other web resources have this kind of certificate error.
> 
> Visit this page:
> https://github.com/dward2/BME547/blob/2019b_Fall/Assignments/heart_rate_sentinel_server_assignment.md#special-note-for-mac-users. This is the version of the Heart Rate Sentinel Server assignment from previous semesters where I have some instructions for Mac users about addressing this problem. Give it a try and please let me know if this helps.

My terminal showed this:
-bash: /Applications/Python 3.7/Install Certificates.command: No such file or directory

FYI, I have my python installed along with anaconda

**Comment by yl642** [comment]
<img width="788" alt="Screen Shot 2020-04-03 at 12 10 08 AM" src="https://user-images.githubusercontent.com/59743242/78323328-7c7a4a00-753f-11ea-93ef-62de1b0df654.png">
https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore/42107877#42107877?newreg=819ef0d3d63740389ddd7206c106b4a0
Look this one!!!
This works!
I guess due to upgrading from MacOS Sierrra to Catalina makes /Applications/Python\ 3.6/./Install\ Certificates.command not work.

**Comment by yl642** [comment]
<img width="666" alt="Screen Shot 2020-04-03 at 12 24 06 AM" src="https://user-images.githubusercontent.com/59743242/78324013-72f1e180-7541-11ea-8d24-65bcd1bd8eb9.png">

Yeah, it works well!
