### ISSUE TITLE
Adalberto Machin- Adalberto-Machin

### ISSUE THREAD

**Issue by Adalberto-Machin** [dward2/BME547#409]
adalberto.machin@duke.edu
macOS

**Comment by dward2** [comment]
@Adalberto-Machin I see you have created a new GitHub ID.  Just to confirm, is this the one you plan on using for the remainder of the semester for this class?

**Comment by Adalberto-Machin** [comment]
Hi Dr. Ward,

Yes, I changed my username to be my name rather than m4c11in, and yes, I plan to use the new username for the rest of the semester. Sorry for any confusion I caused.

Thanks,
Machin
________________________________
