### ISSUE TITLE
Britney Chu - britney-chu CPAP Assignment question

### ISSUE THREAD

**Issue by britney-chu** [dward2/BME547#417]
@dward2 
Hello, 
I was wondering if we should average using the float version of hours or the number of items in the list (integer version of hours). 

Thanks!

**Comment by dward2** [comment]
Good question.  Use the number of items in the list.  So, if the hours was 3.2, and the three numbers are 3, 6, and 8, then the average should be (3 + 6 + 8) / 3.  Do not use the 3.2 as the dividend.
