### ISSUE TITLE
TSH input data

### ISSUE THREAD

**Issue by JellyEvan** [dward2/BME547#42]
In the readme file for the TSH Test Data Conversion assignment its says that the input data will be in a constant order (name, age , gender, tests), however in the 'test_data.txt' file the order of age and gender switches after the second patient.

**Comment by jl532** [comment]
I agree- the order of the name/age/gender/testdata swaps after two patients in the test_data.txt file. @dward2 should we account for potential input data errors like this, or should we rearrange the test_data text so the input data is in a constant order?

**Comment by dward2** [comment]
@JellyEvan @jl532 That is my mistake. The order should be the same for all of the patients.   I will get that fixed tomorrow.   If you are working on that tonight,  go ahead and fix your local copy to have the data in the order that the assignment README.md has.  Sorry for the condition.
