### ISSUE TITLE
Unit Testing When Your Input is in Another Function

### ISSUE THREAD

**Issue by zachthomson6** [dward2/BME547#465]
Hi Dr. Ward,

I'm having trouble running my unit tests because I'm initializing my input for the function in another module. I'm having trouble finding internet resources on how to fix this. Here is my code for email_checker.py, and below it is the first unit test for my prefix_input function.

email_checker.py
```
def is_email():
    prefix_input()


def email_input():
    global email
    email = input("Enter email here: ")
    return email


def prefix_input():
    global prefix
    email_input()
    checker = "@" in email
    if checker == False:
        print(checker)
        print("Email is Unacceptable")
        return checker
    if checker == True:
        for i in range(len(email)):
            if email[i] == "@":
                prefix = email[:i]
                return prefix


if __name__ == "__main__":
    is_email()
```
test_email_checker.py
```
import pytest

@pytest.mark.parametrize("email, expected",
[("zach@duke.edu", "zach"),
 ("bingus@gmail.com", "bingus"),
 ("zachduke.edu", False)
 ])

def test_prefix_input():
    from email_checker import prefix_input
    answer = prefix_input(email)
    assert answer == expected
```
Thanks,
Zach

**Comment by dward2** [comment]
@zachthomson6 I just saw that you had opened an issue on the BME547 GitHub repository page.  As you figured out, since you eventually asked the same question in your classwork repository, your classwork repository is the better place to ask questions about your homework assignment.
