### ISSUE TITLE
Yuanhao Zhao-AsherYuanhao

### ISSUE THREAD

**Issue by AsherYuanhao** [dward2/BME547#511]

**Comment by dward2** [comment]
@AsherYuanhao What operating system are you using?  Windows or macOS?

**Comment by AsherYuanhao** [comment]
macOS, I am still trying to finish the tool setting up ASAP.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: David Ward ***@***.***>
发送时间: Wednesday, September 6, 2023 4:16:04 PM
收件人: dward2/BME547 ***@***.***>
抄送: Yuanhao Zhao ***@***.***>; Mention ***@***.***>
主题: Re: [dward2/BME547] Yuanhao Zhao-AsherYuanhao (Issue #511)


@AsherYuanhao<https://urldefense.com/v3/__https://github.com/AsherYuanhao__;!!OToaGQ!qT85hDDT9shPB6DzjXOvERBlB3Zj0q8a98RrlzzyjQofx6EEzjuQkkLkMKu6zHzJXs4Y6Psj2eyHOAWjvBZBjyqv_g$> What operating system are you using? Windows or macOS?

―
