### ISSUE TITLE
Sentinel Project Request Validation

### ISSUE THREAD

**Issue by chriszhou0916** [dward2/BME547#54]
What should the POST API return if the json supplied doesn't pass validation? i.e. if it is doesn't contain the right fields. We should return a status code, but what should we put in the json?

**Comment by chriszhou0916** [comment]
@dward2

**Comment by dward2** [comment]
It is up to you to decide what it returns.  I would have it return a string that explains why the input was rejected, and also return an error code.

`return error_string, 400`
will return the string `error_string` and an error code of 400 to the calling program.

Then, client programs can check the `r.status_code` of the return, and if it is is not 200 (a good request), the client program can respond to the error.  See <https://www.ietf.org/assignments/http-status-codes/http-status-codes.xml> for a list of error codes.  It doesn't really matter which one you use, as long as you write your client and server code to be using the same one.  

You can visit <http://flask.pocoo.org/docs/1.0/quickstart/#about-responses> for more info about responses.

Please let me know if that doesn't address your question.

Also, look in the upper right corner of this screen.  You should see "Assignees."  If you click on that, a list of names should pop up.  But, your @dward2 did notify me, also.

**Comment by chriszhou0916** [comment]
Thank you so much for your quick response Dr. Ward! I still don't think I can edit the assignees. It might be a permission problem.

**Comment by dward2** [comment]
Yes.  I just noticed that you raised this issue on the class GitHub page and not your own.  When I clicked the link in the e-mail I received when you first raised the issue, I didn't look carefully at the website and just assumed it was in your own.  Yes, I can believe that you might not be able to make assignees as you are not an owner of this site.
