### ISSUE TITLE
Sentinel Server Assignment Modifications

### ISSUE THREAD

**Issue by dward2** [dward2/BME547#60]
Be more clear that we don't want server crashes, with 500 return codes, being the way we validate.  Be more clear that validation should be specific:  actually looking to see if a key is missing, and if it is, capture that and return a 400 error code, rather than letting a KeyError when it couldn't be found cause server code to crash.  Same with checking if the id is numeric.  Don't allow int('abc') to crash and have that be the validation.

Modify write-up so the new_patient age is no longer "user_age", but something more like "patient_age" or just "age".

**Comment by fffairforce** [comment]
ok, I'm working on debuging it.

**Comment by fffairforce** [comment]
Do we have to use this error_handler to capture the error code? I can't quite figure out still. Feeling like when doing only simple callings as the example in class works well, But once I add a stop point in a request it just skipped it.
With Error:
```
Unable to display children:Error resolving variables Traceback (most recent call last):
  File "D:\軟件\Pycharm\PyCharm 2019.1.1\helpers\pydev\_pydevd_bundle\pydevd_comm.py", line 1053, in do_it
    _typeName, val_dict = pydevd_vars.resolve_compound_variable_fields(self.thread_id, self.frame_id, self.scope, self.attributes)
TypeError: cannot unpack non-iterable NoneType object
```
Sorry I must have missed something in class

**Comment by dward2** [comment]
This is most likely an error caused by trying to iterate over a variable that is empty.  For example, if I had code such as this:
```
for i in my_data:
    print(i)
```
If my_data was a variable that had no information in it (meaning its value in python was `None`, then you would get an error similar to above.  This isn't an error you could probably catch using try/except, but would be better prevented by ensuring or checking that the variable to iterate over isn't empty.

Could you share a link to the code that, when you run it, gives you the error above?  I'd be more able to help provide a solution.

**Comment by fffairforce** [comment]
So I'm still running the server code. without input data the class should be empty. So do I have to test from client??
(I have no idea how to send a private repost Url, But I just didn't change my code yet(HRSS.py) to get the error by adding the break point

**Comment by dward2** [comment]
First, I just noticed that this issue conversation is on my class GitHub page.  I'm not sure how that got started.  But, just so you know, the opening comments above for this issue are notes to myself for modifying the assignment in the future.  If you somehow thought they were directed to you specifically, they were not.

**Comment by dward2** [comment]
> So I'm still running the server code. without input data the class should be empty. So do I have to test from client??
> (I have no idea how to send a private repost Url, But I just didn't change my code yet(HRSS.py) to get the error by adding the break point

I still do not understand how you got your error above.  I'm going to open a new issue in your repository. So we can talk there.

**Comment by fffairforce** [comment]
ok, I see. I thought that's something linked. Thanks!
